version: '3.1'

services:
  mariadb:
    image: mariadb:lts
    container_name: mwpa_mariadb
    environment:
      MARIADB_AUTO_UPGRADE: '1'
      MARIADB_INITDB_SKIP_TZINFO: '1'
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'mwpa'
    volumes:
      - mwpaMariadbData:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      mwpaNet:
        ipv4_address: 10.122.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

#  whaleRidgeFindR:
#    image: haimeh/whaleridgefindr:latest
#    container_name: mwpa_whaleridgefindr
#    ports:
#      - "127.0.0.1:8004:8004"
#    networks:
#      mwpaNet:
#        ipv4_address: 10.122.0.4
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "500k"
#        max-file: "50"

#  mwpa:
#    image: mwpa/mwpa:1.0.32
#    build:
#     context: .
#    restart: always
#    container_name: mwpa_server
#    volumes:
#      - ./config.json:/opt/app/config.json
#      - ./imports:/opt/app/imports
#      - ./data:/opt/app/data
#    ports:
#      - 3000:3000
#    networks:
#      mwpaNet:
#        ipv4_address: 10.122.0.3
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "500k"
#        max-file: "50"
#    depends_on:
#      - mariadb

volumes:
  mwpaMariadbData:
    driver: local

networks:
  mwpaNet:
    driver: bridge
    ipam:
      config:
        -  subnet: 10.122.0.0/16
