services:
  mariadb:
    image: mariadb:lts
    container_name: mwpa_mariadb
    environment:
      MARIADB_AUTO_UPGRADE: '1'
      MARIADB_INITDB_SKIP_TZINFO: '1'
      MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "${MARIADB_DATABASE}"
    healthcheck:
      test: [ "CMD", "mariadb", "-u${MARIADB_ROOT_USERNAME}", "-p${MARIADB_ROOT_PASSWORD}", "-e", "use ${MARIADB_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - mwpaMariadbData:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      mwpaNet:
        ipv4_address: 10.122.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

#  whaleRidgeFindR:
#    image: haimeh/whaleridgefindr:latest
#    container_name: mwpa_whaleridgefindr
#    ports:
#      - "127.0.0.1:8004:8004"
#    networks:
#      mwpaNet:
#        ipv4_address: 10.122.0.4
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "500k"
#        max-file: "50"

#  mwpa:
#    image: mwpa/mwpa:1.0.33
#    build:
#     context: .
#    restart: always
#    container_name: mwpa_server
#    environment:
#      MWPA_DB_MYSQL_USERNAME: "${MARIADB_ROOT_USERNAME}"
#      MWPA_DB_MYSQL_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
#      MWPA_DB_MYSQL_DATABASE: "${MARIADB_DATABASE}"
#    volumes:
#      - ./config.json:/opt/app/config.json
#      - ./imports:/opt/app/imports
#      - ./data:/opt/app/data
#    ports:
#      - 3000:3000
#    networks:
#      mwpaNet:
#        ipv4_address: 10.122.0.3
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "500k"
#        max-file: "50"
#    depends_on:
#      mariadb:
#        condition: service_healthy

volumes:
  mwpaMariadbData:
    driver: local

networks:
  mwpaNet:
    driver: bridge
    ipam:
      config:
        -  subnet: 10.122.0.0/16
